name: Send Rich Telegram Report

on:
  workflow_dispatch: # 支持手动点击运行
  # schedule:
    # 每天 UTC 01:00 自动执行（北京时间 09:00）
   # - cron: '0 1 * * *'

jobs:
  run-and-send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # 缓存 pip 包，加快二次执行速度

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python notify.py
